from construct import (Enum, Int8ul, Int16ul)

AreaBitFlags = Enum(
    Int8ul,
    BRINSTAR=0x1,
    KRAID=0x2,
    NORFAIR=0x4,
    RIDLEY=0x8,
    TOURIAN=0x10,
    CRATERIA=0x20,
    CHOZODIA=0x40
)

AreaID = Enum(
    Int8ul,
    BRINSTAR=0,
    KRAID=1,
    NORFAIR=2,
    RIDLEY=3,
    TOURIAN=4,
    CRATERIA=5,
    CHOZODIA=6,
)

ArmCannonDirection = Enum(
    Int8ul,
    FORWARD=0,
    DIAGONAL_UP=1,
    DIAGONAL_DOWN=2,
    UP=3,
    DOWN=4,
    NONE=5
)

BGProperty = Enum(
    Int8ul,
    NONE=0,
    RLE_COMPRESSED=0x10,
    MOVING_BG2=0x31,
    LZ77_COMPRESSED=0x40,
    DARK_ROOM=0x45,
    BG3_STARTS_FROM_BOTTOM=0x46
)

BackgroundFade = Enum(
    Int8ul,
    NOTHING=0,
    FADE_TO_BLACK=1,
    FADE_TO_WHITE=2
)

BeamBombStatus = Enum(
    Int8ul,
    LONG_BEAM=0x1,
    ICE_BEAM=0x2,
    WAVE_BEAM=0x4,
    PLASMA_BEAM=0x8,
    CHARGE_BEAM=0x10,
    BOMBS=0x80
)

BeforeAfterEventFlag = Enum(
    Int8ul,
    AFTER=0,
    BEFORE=1
)

BlockReformType = Enum(
    Int8ul,
    NONE=0,
    NO_OR_NEVER_REFORM=1,
    REFORM=2,
    BOMB_CHAIN=3,
    TANK=4
)

BlockWeaknessFlags = Enum(
    Int8ul,
    NONE=0x0,
    BEAM=0x1,
    BOMB_OR_PISTOL=0x2,
    MISSILE=0x4,
    SUPER_MISSILE=0x8,
    POWER_BOMB=0x10,
    SPEEDBOOST=0x20,
    SPEEDBOOST_GROUND=0x40,
    SCREW_ATTACK=0x80,
    BOMB_CHAIN=0x1000 # seems to not fit in 1B? NOTE
)

BombChainType = Enum(
    Int8ul,
    VERTICAL1=0,
    VERTICAL2=1,
    VERTICAL3=2,
    VERTICAL4=3,
    HORIZONTAL1=4,
    HORIZONTAL2=5,
    HORIZONTAL3=6,
    HORIZONTAL4=7
)

BreakableBlockType = Enum(
    Int8ul,
    NONE=0,
    SHOT_BLOCK_REFORM=0x1,
    BOMB_BLOCK_REFORM=0x2,
    SPEEDBOOSTER_REFORM=0x3,
    CRUMBLE=0x4,
    SLOW_CRUMBLE=0x5,
    MISSILE_NEVERREFORM=0x6,
    MISSILE_NOREFORM=0x7,
    SUPERMISSILE_NEVERREFORM=0x8,
    SUPERMISSILE_NOREFORM=0x9,
    POWERBOMB_NEVERREFORM=0xA,
    SCREWATTACK_NOREFORM=0xB,
    SPEEDBOOSTER_NOREFORM=0xC,
    BOMB_NEVERREFORM=0xD,
    VERTICALBOMBCHAIN1=0xE,
    VERTICALBOMBCHAIN2=0xF,
    VERTICALBOMBCHAIN3=0x10,
    VERTICALBOMBCHAIN4=0x11,
    HORIZONTALBOMBCHAIN1=0x12,
    HORIZONTALBOMBCHAIN2=0x13,
    HORIZONTALBOMBCHAIN3=0x14,
    HORIZONTALBOMBCHAIN4=0x15,
)

ButtonInput = Enum(
    Int16ul,
    A=0x1,
    B=0x2,
    SELECT=0x4,
    START=0x8,
    RIGHT=0x10,
    LEFT=0x20,
    UP=0x40,
    DOWN=0x80,
    R=0x100,
    L=0x200
)

ChozoHintCheckType = Enum(
    Int8ul,
    BEAM_BOMBS=0,
    SUIT_MISC=1,
    EVENT=2
)

ChozoHintIcon = Enum(
    Int8ul,
    TARGET=0x1,
    UP_ELEVATOR=0x2,
    DOWN_ELEVATOR=0x3,
    GREEN_FLAME=0x8,
    GREEN_FLAME_MOVESUPDOWN=0xA,
    PINK_FLAME=0xC,
    PINK_FLAME_MOVESUPDOWN=0xE
)

ChozoHintLocation = Enum(
    Int16ul,
    LONG_BEAM=0x1,
    BOMBS=0x2,
    ICE_BEAM=0x4,
    SPEED_BOOSTER=0x8,
    HI_JUMP=0x10,
    VARIA_SUIT=0x20,
    WAVE_BEAM=0x40,
    SCREW_ATTACK=0x80,
    KRAID_FLAME=0x100,
    RIDLEY_FLAME=0x200
)

ClipdataAffectingAction = Enum(
    Int8ul,
    REMOVE_SOLID=0x1,
    MAKE_SOLID=0x2,
    MAKE_STOP_ENEMY=0x3,
    MAKE_NON_POWERGRIP=0x4,
    BOMBCHAIN_UNUSED=0x5,
    UNUSED=0x6,
    BEAM=0x7,
    BOMB_PISTOL=0x8,
    MISSILE=0x9,
    SUPER_MISSILE=0xA,
    POWER_BOMB=0xB,
    SPEEDBOOST=0xC,
    SPEEDBOOST_GROUND=0xD,
    SCREW_ATTACK=0xE,
    BOMB_CHAIN=0xF
)

ClipdataBehaviorType = Enum(
    Int8ul,
    AIRORSOLID=0x0,
	ELEVATORDOWNBLOCK=0x1,
	ELEVATORUPBLOCK=0x2,
	DOORTRANSITIONBLOCK=0x3,
	VERTICALUPTRANSITIONBLOCK=0x4,
	VERTICALDOWNTRANSITIONBLOCK=0x5,
	NONPOWERGRIP=0x6,
	STOPENEMYBLOCK_SOLID=0x7,
	SPACEPIRATEZONELINE=0x8,
	SPACEPIRATEWALLJUMPPOINT=0x9,
	SHOTBLOCK_NEVERREFORM=0x10,
	TOPLEFTSHOTBLOCK_NEVERREFORM=0x11,
	TOPRIGHTSHOTBLOCK_NEVERREFORM=0x12,
	BOTTOMLEFTSHOTBLOCK_NEVERREFORM=0x13,
	BOTTOMRIGHTSHOTBLOCK_NEVERREFORM=0x14,
	SHOTBLOCK_NOREFORM=0x15,
	TOPLEFTSHOTBLOCK_NOREFORM=0x16,
	TOPRIGHTSHOTBLOCK_NOREFORM=0x17,
	BOTTOMLEFTSHOTBLOCK_NOREFORM=0x18,
	BOTTOMRIGHTSHOTBLOCK_NOREFORM=0x19,
	SHOTBLOCK_REFORM=0x1A,
	BOMBBLOCK_NEVERREFORM=0x1B,
	BOMBBLOCK_REFORM=0x1C,
	MISSILEBLOCK_NEVERREFORM=0x1D,
	MISSILEBLOCK_NOREFORM=0x1E,
	SUPERMISSILEBLOCK_NEVERREFORM=0x1F,
	SUPERMISSILEBLOCK_NOREFORM=0x20,
	SPEEDBOOSTBLOCK_NOREFORM=0x21,
	SPEEDBOOSTBLOCK_REFORM=0x22,
	CRUMBLEBLOCK=0x23,
	POWERBOMBBLOCK_NEVERREFORM=0x24,
	SCREWATTACKBLOCK_NOREFORM=0x25,
	VERTICALBOMBCHAIN1=0x26,
	VERTICALBOMBCHAIN2=0x27,
	VERTICALBOMBCHAIN3=0x28,
	VERTICALBOMBCHAIN4=0x29,
	HORIZONTALBOMBCHAIN1=0x2A,
	HORIZONTALBOMBCHAIN2=0x2B,
	HORIZONTALBOMBCHAIN3=0x2C,
	HORIZONTALBOMBCHAIN4=0x2D,
	SLOWCRUMBLEBLOCK=0x2E,
	HIDDENENERGYTANK=0x34,
	HIDDENMISSLETANK=0x35,
	HIDDENSUPERMISSLETANK=0x36,
	HIDDENPOWERBOMBTANK=0x37,
	ENERGYTANK=0x38,
	MISSLETANK=0x39,
	SUPERMISSLETANK=0x3A,
	POWERBOMBTANK=0x3B,
	UNDERWATERENERGYTANK=0x3C,
	UNDERWATERMISSILETANK=0x3D,
	UNDERWATERSUPERMISSILETANK=0x3E,
	UNDERWATERPOWERBOMBTANK=0x3F,
	WATER=0x40,
	STRONGLAVA=0x41,
	WEAKLAVA=0x42,
	ACID=0x43,
	BG0TRIGGEROPAQUE=0x44,
	BG0TRIGGERTRANSPARENTLEVEL1=0x45,
	BG0TRIGGERTRANSPARENTLEVEL2=0x46,
	BG0TRIGGERTRANSPARENTLEVEL3=0x47,
	BG0TRIGGERTRANSPARENTLEVEL4=0x48,
	BG0TRIGGERTRANSPARENTLEVEL5=0x49,
	BG0TRIGGER100TRANSPARENT=0x4A,
	BG0TRIGGERBRIGHTER1=0x4B,
	BG0TRIGGERBRIGHTER2=0x4C,
	BG0TRIGGERBRIGHTER3=0x4D,
	BG0TRIGGERBRIGHTER4=0x4E,
	BG0TRIGGERDEFAULTTRANSPARENCY=0x4F,
	WETGROUND=0x50,
	DUSTYGROUND=0x51,
	UNUSEDSOLID_1E=0x52,
	BUBBLYGROUND=0x53,
	VERYDUSTYGROUND=0x54,
	GRAYDOOR=0x80,
	REGULARDOOR=0x81,
	MISSILEDOOR=0x82,
	SUPERMISSILEDOOR=0x83,
	POWERBOMBDOOR=0x84
)

ClipdataCollisionType = Enum(
    Int8ul,
    AIR=0x0,
	SOLID=0x1,
	LEFTSTEEPFLOORSLOPE=0x2,
	RIGHTSTEEPFLOORSLOPE=0x3,
	LEFTUPPERSLIGHTFLOORSLOPE=0x4,
	LEFTLOWERSLIGHTFLOORSLOPE=0x5,
	RIGHTLOWERSLIGHTFLOORSLOPE=0x6,
	RIGHTUPPERSLIGHTFLOORSLOPE=0x7,
	ENEMYONLY=0x8,
	STOPENEMYBLOCK=0x9,
	TANK=0xA,
	DOOR=0xB,
	PASSTHROUGHBOTTOM=0xC
)

CollisionCheck = Enum(
    Int8ul,
	AIRORNOCOLLISION=0x0,
	LEFTSLIGHTFLOORSLOPE=0x2,
	RIGHTSLIGHTFLOORSLOPE=0x3,
	LEFTSTEEPFLOORSLOPE=0x4,
	RIGHTSTEEPFLOORSLOPE=0x5,
	PASSTHROUGHBOTTOM=0x10,
	SOLIDORCOLLISION=0x11
)

Cutscene = Enum(
    Int8ul,
	NONE=0x0,
	SAMUSINTROTEXT=0x1,
	SAMUSZEBESESCAPETEXT=0x2,
	SAMUSZEBESESCAPEFINALTEXT=0x3,
	MOTHERBRAINCLOSEUP=0x4,
	KRAIDFIGHTSTART=0x5,
	TOURIANELEVATORSTATUEACTIVATING=0x6,
	RIDLEYINSPACE=0x7,
	RIDLEYLANDING=0x8,
	RIDLEYFIGHTSTART=0x9,
	TOURIANMETROIDS=0xA,
	BEFORERUINSTESTFIGHT=0xB,
	OBTAININGFULLYPOWEREDSUIT=0xC,
	MECHARIDLEYSEESSAMUS=0xD,
	ACTIVATINGESCAPESHIP=0xE
)

CutsceneRequest = Enum(
    Int8ul,
	NONE=0x0,
	ESCAPINGCHOZODIA=0x1,
	ESCAPEDFAILED=0x2,
	ESCAPINGZEBES=0x3,
	OBTAININGFULLYPOWEREDSUIT=0x4,
	RIDLEYFIGHTSTART=0x5,
	TOURIANELEVATORSTATUEACTIVATING=0x6,
	SAMUSINTROTEXT=0x7,
	ACTIVATINGESCAPESHIP=0x8
)

CutsceneSpecialEffectStatus = Enum(
    Int8ul,
	NONE=0x0,
	ONOBJ=0x1,
	OBJEFFECTENDED=0x2,
	ONBG=0x4,
	BGEFFECTENDED=0x8
)

# TODO undocumented
DebrisCloudType = Enum(
    Int8ul,
    TODO=0
)

DemoStatus = Enum(
    Int8ul,
    NONE=0,
    PLAYING=1,
    LOADING=16
)

DiagonalAim = Enum(
    Int8ul,
    NONE=0,
    DIAGONALLYUP=1,
    DIAGONALLYDOWN=2
)

Difficulty = Enum(
    EASY=0,
    NORMAL=1,
    HARD=2
)

Direction = Enum(
    Int8ul,
    RIGHT=0x10,
    LEFT=0x20,
    UP=0x40,
    DOWN=0x80
)

DoorType = Enum(
    Int8ul,
    AREA_CONNECTION=1,
    NO_HATCH=2,
    OPEN_HATCH=3,
    CLOSED_HATCH=4,
    REMOVE_MOTHERSHIP=5,
    SET_MOTHERSHIP=6,
    LOADS_EVENT_BASED_ROOM=32,
    DISPLAYS_LOCATION_NAME=64
)